---
- name: Download and unarchive the package
  shell: "cd /tmp && wget -q --auth-no-challenge --header=\"Accept:application/octet-stream\" https://{{ sre_tooling_bearer_token }}:@api.github.com/repos/onaio/sre-tooling/releases/assets/{{ sre_tooling_asset_id }} -O - | tar xz"
  changed_when: false

- name: Copy the SRE Tooling binary
  copy:
    src: "/tmp/sre-tooling"
    remote_src: true
    dest: "{{ sre_tooling_install_path }}"
    owner: "{{ sre_tooling_system_user }}"
    group: "{{ sre_tooling_system_group }}"
    mode: 0551

- name: Create the SRE Tooling environment file
  template:
    src: "sre_tooling_environment_file"
    dest: "{{ sre_tooling_environment_file }}"
    owner: "{{ sre_tooling_system_user }}"
    group: "{{ sre_tooling_system_group }}"
    mode: 0640

- name: Create the SRE Tooling data directory
  file:
    path: "{{ sre_tooling_data_dir }}"
    state: directory
    owner: "{{ sre_tooling_system_user }}"
    group: "{{ sre_tooling_system_group }}"
    mode: 0750
