---
- name: Converge
  hosts: all
  vars:
    sre_tooling_enabled_services:
      - infra-index-update
      - monitor-nifi-fb-ingest
  tasks:
    - name: "Include role"
      include_role:
        name: "ansible-sre-tooling"
