---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-ubuntu-18.04
    image: solita/ubuntu-systemd:18.04
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
