---
# This is a playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Run systemctl is-enabled
      command: "systemctl is-enabled {{ _cur_service }}"
      register: _service_statuses
      loop:
        - sre-tooling-infra-index-update.timer
        - sre-tooling-monitor-nifi-fb-ingest.timer
      loop_control:
        loop_var: _cur_service

    - name: Check if systemd service/timer is enabled
      assert:
        that: _cur_service_status.rc == 0
      loop: "{{ _service_statuses.results }}"
      loop_control:
        loop_var: _cur_service_status
